---
title: "ESM211 Group Project Data Viz"
author: "Taylor Lockmann"
date: "2/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup


```{r}
# Read in libraries
library(tidyverse)
library(here)
library(lubridate)
```

```{r}
# Read in the data to use
squid_fishing_data <- read.csv(here("data", "fishing_effort_per_block.csv"))
```


## Exploratory Data Viz

### Lbs vs # Receipts

```{r}
ggplot(data = squid_fishing_data, aes(x = catch_receipts, y = catch_lbs))+
  geom_point()+
  theme_bw()+
  labs(title = "Pounds of Squid Caught vs Number of Receipts Reported",
       subtitle = "Including zero receipts or lbs caught")
```


### Fishing effort over time

```{r}
ggplot(data = squid_fishing_data)+
  geom_point(aes(x = landing_month, y = catch_per_receipts, color = landing_year))+
  theme_bw()+
  labs(title = "Pounds of Squid Caught Per Landing Receipt")
```

# 2/24 notes
# Next steps: consolidate catch per unit effort into one value per year. Then look at trends across time, especially identifying El Nino years.

```{r}
# Wrangle some more data
squid_fishing_no_na <- squid_fishing_data %>% 
  drop_na() %>% # Drop NAs from our dataframe
  group_by(landing_year, landing_month) %>% # Group data according to month and year
  summarise_at(vars(catch_per_receipts),
               list(avg_cpu = mean)) # Summarize average of catch_per_receipts

squid_fishing_no_na$landing_year <- as.factor(squid_fishing_no_na$landing_year)
```


```{r}
# Make a graph of CPU
ggplot(data = squid_fishing_no_na)+
  geom_point(aes(x = landing_month, y = avg_cpu, color = landing_year))+
  geom_line(aes(x = landing_month, y = avg_cpu, color = landing_year))+
  theme_bw()

  
```


```{r}
# Make a graph with consecutive years

squid_tibble<- squid_fishing_no_na %>% 
  mutate(date = make_date(year=landing_year, month=landing_month))

ggplot(data = squid_tibble)+
  geom_point(aes(x = date, y = avg_cpu))+
  geom_line(aes(x = date, y = avg_cpu))+
  theme_bw()
```
 


