---
title: "Untitled"
author: "Craig Stuart"
date: "3/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(popbio)
library(tidyverse)
```

Calculate R0 with p values
```{r}
R0_calculated<-c()
for(i in seq(from = 0.1, to = 1, by=0.01)) {
  R0=3844*(i)^5
  R0_calculated <- c(R0_calculated, R0)
  }

R0_calculated
```


Calculate R0 with p values
```{r}
#Make a vector of the p values we used to calculate R0
pvalue <- c()
pvalue[1] = 0.1
for(i in 2:91) {
  pvalue[i] = pvalue[i-1]+0.01
}

pvalue

#Make a data frame of the two vectors
R0_data <- data.frame(R0_calculated, pvalue)

#Plot the graph of the relationship between the p value and R0
ggplot(R0_data, aes(x = pvalue, y = R0_calculated)) +
  geom_line() +
  theme_minimal() +
  xlab("p-value") +
  ylab("R0")

#This is my exploratory plot of R0
#plot(my_vec, pch = 16, ylab = "R0", xlab = "p")
```

```{r}
#Make a smaller subset of the p-values
p_lessthan70 <- R0_data %>% 
  filter(pvalue <= 0.70)

#Plot it with vertical lines at bounds of p estimates
ggplot(p_lessthan70, aes(x = pvalue, y = R0_calculated)) + 
  geom_line() +
  geom_vline(xintercept = 0.4) +
  geom_vline(xintercept = 0.7) +
  theme_minimal() +
  xlab("p-value") +
  ylab("R0")
```

```{r}
#Make an even smaller subset of the data
p_lessthan35 <- R0_data %>% 
  filter(pvalue <= 0.35)

#And plot it
ggplot(p_lessthan35, aes(x = pvalue, y = R0_calculated)) +
  geom_line() + theme_minimal() +
  xlab("p-value") + ylab("R0") +
  geom_hline(yintercept = 1, col = "red") +
  annotate("text", x = 0.1, y = 1.75, label = "R0 = 1", col = "red")
```


Build Age Structure Matrix Model

```{r}
#Define the ages 
stages = c("0", "1")


#Define the matrix
A = matrix(c(0,3844,0.5,0),nrow=2, byrow=T,dimnames=list(stages,stages))

#check the matrix
A

#Define an initial population structure
N0=c(20,20)

#Project the matrix population model K time steps
K<-50
projA=pop.projection(A,N0,K)

#the population growth rate (lambda). Above 1, population growth. Below 1, populaiton decline.
projA$lambda

#Plot the population size projection
plot(projA$pop.size,pch=16, type='b',ylab="Population Size",xlab="Time Step")
```

